### ISSUE TITLE
Species with conservation status being miscounted

### ISSUE THREAD

**Issue by kitenetter** [BiologicalRecordsCentre/Pantheon#111]
Several of the Habitats & resources: tabular views show a column with "number of species that have a conservation status", but this number is often too large, i.e. when you click on a number that says "6" for example there may only be one species shown.

Probably relates to closed issue #102 

Possibly also relates to #103 ?

**Comment by kitenetter** [comment]
Have just been informed that the duplications are also affecting the SQI scores, and making them higher than they should be.

**Comment by johnvanbreda** [comment]
Fixed. There was a mistake in the way I'd imported the designations so I've re-imported them. SQI scores still to do.

**Comment by kitenetter** [comment]
There are still a few duplications cropping up, e.g. this from http://www.brc.ac.uk/pantheon/species-for-sample?dynamic-sample_id=678547&dynamic-sample_type=sample&dynamic-trait_term_id=14001&dynamic-trait_attr_id=184&dynamic-has_any_designation=t

![image](https://cloud.githubusercontent.com/assets/16039111/22822356/0c3d05e4-ef77-11e6-9858-b0d23326ec0f.png)

**Comment by HDean** [comment]
See also:



From: Webb, Jon (NE) [mailto:Jon.Webb@naturalengland.org.uk] 
Sent: 09 February 2017 11:59
To: John van Breda <john.vanbreda@biodiverseit.co.uk>
Cc: Dean, Hannah J. <hajd@ceh.ac.uk>
Subject: Conservation Status score

Hi John, 
 
The conservation status score is still not displaying correctly…
 
 
 
 
For Grimsthorpe test data it suggest that there are 60 ‘species with a conservation status’. If you then click on the ‘Conservation status’ it displays 62 species, but these include those with LC (least concern) and None. From just counting those with a threat/rarity status it seems to be 47, which is the number that should be displayed under ‘species with a conservation status’ and the number of species listed when you click on the underlying list in ‘Conservation status’.
 
 
Cheers
 
Jon

**Comment by johnvanbreda** [comment]
I've fixed the duplications reported by @kitenetter as well as the last problem with over-counted conservation statuses.
Please can I have a clear example of where the SQI looks wrong.

**Comment by kitenetter** [comment]
Hi @johnvanbreda the SQIs seem to be calculating okay now, thanks, I've checked a sample from the person who raised the issue and I can't see any errors in the calculation.

@HDean the same person did query the scores that had been assigned to the species however. His example was the hoverfly Pocota personata. This has a SQS of 16, but it has become more widespread and its current status is listed as "LC, NS", which ought to equate to an SQS of 4.

Are there further database updates to the SQS still to be applied, or is this something that NE have scored incorrectly in the raw data?

**Comment by HDean** [comment]
@kitenetter 
The scores have not yet been reloaded so are still showing the old ones. The conservation status were done as separate file so have already been updated.

**Comment by kitenetter** [comment]
@johnvanbreda @HDean I'm still a bit confused here. The counts shown in the habitat tables are correct now as far as I can tell, but when you click on the red conservation status text to see the species list for those that have a status the resulting table is still including "LC" and "None" species. Not sure if that is a bug, or the result of the various updates still working their way through.

**Comment by johnvanbreda** [comment]
It's definitely a quirk/feature/bug. The species lists show all statuses including LC and None. The habitat tables exclude LC and none. So, when you follow the link to the species tables to show all species with a status, you get a list that shows LC and None even though they weren't visible in the habitat tables.

I suggest that when we show a species list filtered to only species with a status, the filter should ignore LC, None and the other designations we skip in the habitat tables. Do you agree?

**Comment by kitenetter** [comment]
I agree - it seems confusing to list one set of status terms in the habitat table and then be presented with a different set when opening up the species table.

If anyone needs the LC, None terms etc. they will still be in the full species list table (if I've understood correctly).

**Comment by HDean** [comment]
I also agree! Species with "LC" or "None" should only show up in the species index.

**Comment by johnvanbreda** [comment]
Agreed - done
